#print("Hello World")
print("Hello!")
print("Welcome to CSC 1301 Principles of Computer Science I Course!")
print("Our class is held every Tuesday and Thrusday at 5:30pm.")
print("Our Lab session is held every Tuesday at 11:00am")